In [44]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [45]:
df = pd.read_csv(r"C:\Users\user\Downloads\archive (2)\melb_data.csv")
print(df.head())

       Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan

  Propertycount
0        4019.0
1        4019.0
2        4019.0
3        4019.0
4        4019.0

[5 rows x 21 columns]

In [46]:
df.shape

(13580, 21)

In [47]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [49]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [50]:
df.isnull(),sum()

TypeError: sum() takes at least 1 positional argument (0 given)

In [51]:
df.isnull.sum()

AttributeError: 'function' object has no attribute 'sum'

In [52]:
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [53]:
df_mean=df.copy()
mean_building_area=df_mean["BuildingArea"].mean()
mean_building_area=df_mean["BuildingArea"].fillna(mean_building_area)

In [54]:
mean_building_area

0        151.96765
1         79.00000
2        150.00000
3        151.96765
4        142.00000
           ...
13575    151.96765
13576    133.00000
13577    151.96765
13578    157.00000
13579    112.00000
Name: BuildingArea, Length: 13580, dtype: float64

In [55]:
df_mean["BuildingArea"].isnull().sum(
)

6450

In [56]:
df_ffill=df.copy()
df_ffill["Car"]=df_ffill["Car"].ffill()
df_ffill["Car"].isnull().sum()

0

In [57]:
df_ffill["Car"].isnull().sum()

0

In [60]:
df_median=df.copy()
comparison=pd.DataFrame({
    "Original":df["BuildingArea"].head(15),
    "Mean Imputd":df_mean["BuildingArea"].head(15),
    
    "Original":df["YearBuilt"].head(15),
    "Median Imputd":df_median["YearBuilt"].head(15),
    
    "Original":df["Car"].head(15),
    "forward fill":df_median["Car"].head(15),
})

In [61]:
comparison

    Original  Mean Imputd  Median Imputd  forward fill
0        1.0          NaN            NaN           1.0
1        0.0         79.0         1900.0           0.0
2        0.0        150.0         1900.0           0.0
3        1.0          NaN            NaN           1.0
4        2.0        142.0         2014.0           2.0
5        0.0          NaN            NaN           0.0
6        0.0        210.0         1910.0           0.0
7        2.0        107.0         1890.0           2.0
8        1.0          NaN            NaN           1.0
9        2.0         75.0         1900.0           2.0
10       1.0          NaN            NaN           1.0
11       2.0        190.0         2005.0           2.0
12       1.0         94.0         2009.0           1.0
13       1.0          NaN            NaN           1.0
14       1.0          NaN            NaN           1.0

In [68]:

df_processed = df. copy()
council_mode = df_processed["CouncilArea"].mode()[0]
df_processed["CouncilArea"] = df_processed["CouncilArea"].fillna(council_mode)
df_processed ["CouncilArea"].isnull() .sum()

0

In [69]:
council_mode

'Moreland'

In [70]:
df_processed ["CouncilArea"].isnull() .sum()

0

In [84]:

df_encoded = pd.get_dummies(
df_processed, columns=[ "Type","Method"],
dtype=int
)
print ("\nDataset After One-Hot Encoding:") 
print (df_encoded.head())

Dataset After One-Hot Encoding:
       Suburb           Address  Rooms      Price SellerG       Date  \
0  Abbotsford      85 Turner St      2  1480000.0  Biggin  3/12/2016
1  Abbotsford   25 Bloomburg St      2  1035000.0  Biggin  4/02/2016
2  Abbotsford      5 Charles St      3  1465000.0  Biggin  4/03/2017
3  Abbotsford  40 Federation La      3   850000.0  Biggin  4/03/2017
4  Abbotsford       55a Park St      4  1600000.0  Nelson  4/06/2016

   Distance  Postcode  Bedroom2  Bathroom  ...             Regionname  \
0       2.5    3067.0       2.0       1.0  ...  Northern Metropolitan
1       2.5    3067.0       2.0       1.0  ...  Northern Metropolitan
2       2.5    3067.0       3.0       2.0  ...  Northern Metropolitan
3       2.5    3067.0       3.0       2.0  ...  Northern Metropolitan
4       2.5    3067.0       3.0       1.0  ...  Northern Metropolitan

   Propertycount  Type_h  Type_t Type_u  Method_PI  Method_S Method_SA  \
0         4019.0       1       0      0          0         1         0
1         4019.0       1       0      0          0         1         0
2         4019.0       1       0      0          0         0         0
3         4019.0       1       0      0          1         0         0
4         4019.0       1       0      0          0         0         0

   Method_SP  Method_VB
0          0          0
1          0          0
2          1          0
3          0          0
4          0          1

[5 rows x 27 columns]

In [85]:
df_label = df.copy()

label_encoder = LabelEncoder()

df_label["CouncilArea_Encoded"] = label_encoder.fit_transform(df_label["CouncilArea"].astype(str))

print("\nLabel Encoding of CouncilArea:")
print(df_label[["CouncilArea", "CouncilArea_Encoded"]].head(10))

Label Encoding of CouncilArea:
  CouncilArea  CouncilArea_Encoded
0       Yarra                   31
1       Yarra                   31
2       Yarra                   31
3       Yarra                   31
4       Yarra                   31
5       Yarra                   31
6       Yarra                   31
7       Yarra                   31
8       Yarra                   31
9       Yarra                   31